owner_name: seq
title: Steam Compact
description: A skin for the Steam client, by seq
google_analytics: 
show_downloads: true
theme: jekyll-theme-midnight
"zip_url": "https://github.com/badanka/Compact/releases/latest"

gems:
  - jekyll-mentions
